### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by Kuuuube** [TheBlueOompaLoompa/BetterCalibrator#6]
Hi @TheBlueOompaLoompa, occasionally users will install this plugin with no idea what it does or what it's for and they certainly aren't reading the readme/wiki to set it up. It causes a bit of pain for the OTD support figuring out what these users have done to make OTD crash/not work.

The issues with the plugin erroring when not set up were fixed in #2 but there was never a release made for this. It would be great if you could make one.

If you're very busy and short on time I can even update the plugin repo for the new release on your behalf.

**Comment by TheBlueOompaLoompa** [comment]
Yeah sorry, I've been busy with school. I will change repo permissions to add you. I don't have time right now to work on this.

**Comment by Kuuuube** [comment]
Thank you. I've pushed a release and made a PR to the plugin repo https://github.com/OpenTabletDriver/Plugin-Repository/pull/110. Closing this now.
